
export const READ_HELLO_SAGA = 'READ_HELLO_SAGA';

export const READ_HELLO_LOADING = 'READ_HELLO_LOADING';
export const READ_HELLO_SUCCESS = 'READ_HELLO_SUCCESS';
export const READ_HELLO_ERROR = 'READ_HELLO_ERROR';